version: '3'

services:
  postgres:
    image: postgres:alpine3.19
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: apaez
      POSTGRES_USER: apaez
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  

  redis:
    image: redis:alpine3.19
    container_name: redis
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"  

volumes:
  postgres_data:
  redis_data:
